default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: video_chats_development
  username: <%= ENV["VIDEO_CHAT_DB_USER"] %>
  password: <%= ENV["VIDEO_CHAT_DB_PASS"] %>

test:
  <<: *default
  database: video_chats_test

production:
  primary: &primary_production
    <<: *default
    database: video_chats_production
    username: <%= ENV["VIDEO_CHAT_DB_USER"] %>
    password: <%= ENV["VIDEO_CHAT_DB_PASS"] %>
  cache:
    <<: *primary_production
    database: video_chats_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: video_chats_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: video_chats_production_cable
    migrations_paths: db/cable_migrate